name = "DrWatsonSim"
uuid = "2380ba89-4eda-4b1c-913c-f10e6d4aa00f"
authors = ["Sebastian Pech <sebastian.pech@me.com> and contributors"]
version = "0.1.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"

[compat]
BSON = "0.2"
julia = "1"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Pkg", "Dates"]
